test:
  adapter: postgresql
  encoding: unicode
  database: storyitr8_test
  pool: 5
development:
  adapter: postgresql
  encoding: unicode
  database: storyitr8_test_development
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: storyitr8_production
  pool: 5
